services:
  db:
    container_name: db
    image: postgres:15
    environment:
      POSTGRES_DB: 'app'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  shadow_db:
    container_name: shadow_db
    image: postgres:15
    environment:
      POSTGRES_DB: 'app'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '54321:5432'
    volumes:
      - shadow_db:/var/lib/postgresql/data

volumes:
  db:
  shadow_db:
