services:
  db:
    container_name: db
    image: postgres:15
    environment:
      POSTGRES_DB: 'app'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - '9000:9000' # API port
      - '9001:9001' # Console port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

volumes:
  db:
  minio_data:
