# Use Node base image
FROM node:18-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Copy source code
COPY . .

# Generate Prisma client
RUN yarn prisma generate

# Build Next.js app
RUN yarn next build

CMD ["sh", "-c", "yarn prisma migrate reset --force && yarn next start"]