name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  setup:
    uses: ./.github/workflows/setup-ssh.yml
    secrets:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      ENV_VARS: ${{ secrets.ENV_VARS }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECURITY_GROUP_ID: ${{ secrets.AWS_SECURITY_GROUP_ID }}

  deploy:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy files to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "mkdir -p ~/lifehacksjapan-forum"
          scp -r . ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/lifehacksjapan-forum

      - name: Deploy Docker on EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/lifehacksjapan-forum
            docker stop lifehacksjapan-container || true && docker rm lifehacksjapan-container || true
            docker build -f docker/Dockerfile.prod -t lifehacksjapan-image .
            docker run -d -p 3000:3000 --env-file .env --name lifehacksjapan-container lifehacksjapan-image
          EOF

  revoke:
    needs: deploy
    if: always()
    uses: ./.github/workflows/revoke-ip.yml
    with:
      runner_ip: ${{ needs.setup.outputs.runner_ip }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECURITY_GROUP_ID: ${{ secrets.AWS_SECURITY_GROUP_ID }}
