name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get runner IP address
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Whitelist runner IP address
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id ${{ secrets.AWS_SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: Setup SSH
        run: |
          # Create .ssh directory with correct permissions
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Write SSH key with proper format
          echo -e "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Start SSH agent
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

          # Create known_hosts if it doesn't exist
          touch ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

          # Add host key to known_hosts
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

          # Test SSH connection with verbose output
          ssh -v -o BatchMode=yes -o StrictHostKeyChecking=no "${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}" "echo 'SSH connection successful'"

      - name: Clean up EC2 directory
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "rm -rf ~/lifehacksjapan-forum && mkdir -p ~/lifehacksjapan-forum"

      - name: Create env file
        run: |
          ssh -o StrictHostKeyChecking=no "${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}" << 'EOF'
            echo '${{ secrets.ENV_VARS }}' > ~/lifehacksjapan-forum/.env
          EOF

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy files to EC2
        run: |
          # Copy all files except node_modules and .git
          rsync -avz --exclude 'node_modules' --exclude '.git' . ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/lifehacksjapan-forum/

      - name: Deploy Docker on EC2
        run: |
          ssh -o ServerAliveInterval=60 -o ServerAliveCountMax=3 ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Clean up only what we need
            echo "Cleaning up Docker..."
            
            # Stop and remove our container if it exists
            docker stop lifehacksjapan-container || true
            docker rm lifehacksjapan-container || true
            
            # Remove our specific image
            docker rmi lifehacksjapan-image || true
            
            # Remove dangling images (images without tags)
            docker image prune -f
            
            # Remove unused volumes
            docker volume prune -f

            # Deploy
            cd ~/lifehacksjapan-forum
            
            # Build with no cache and increased memory limit
            echo "Building Docker image..."
            docker build \
              --no-cache \
              --memory=4g \
              --memory-swap=4g \
              -f docker/Dockerfile.prod \
              -t lifehacksjapan-image .

            # Run container
            echo "Starting container..."
            docker run -d -p 3000:3000 --env-file .env --name lifehacksjapan-container lifehacksjapan-image

            # Show Docker status
            echo "Docker status:"
            docker ps
            docker system df
          EOF

      - name: Revoke runner IP address
        if: always()
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.AWS_SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
