name: Run Prisma Migrations

on:
  workflow_dispatch:

jobs:
  setup:
    uses: ./.github/workflows/setup-ssh.yml
    secrets:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      ENV_VARS: ${{ secrets.ENV_VARS }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECURITY_GROUP_ID: ${{ secrets.AWS_SECURITY_GROUP_ID }}

  migrate:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run Prisma Migrations on EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/lifehacksjapan-forum
            if [ ! -f .env ]; then
              echo ".env file not found. Aborting migration."
              exit 1
            fi
            yarn prisma migrate deploy --schema=./prisma/schema.prisma
          EOF

      - name: Revoke runner IP address
        if: always()
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.AWS_SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ needs.setup.outputs.runner_ip }}/32
