name: Setup SSH and Environment

on:
  workflow_call:
    secrets:
      EC2_HOST:
        required: true
      EC twice_USER:
        required: true
      EC2_SSH_KEY:
        required: true
      ENV_VARS:
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          # Create .ssh directory
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Write SSH key with proper format
          echo -e "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Start SSH agent
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

          # Add host key with retry
          for i in {1..3}; do
            if ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts; then
              echo "Successfully added host key"
              break
            else
              echo "Attempt $i failed, retrying..."
              sleep 2
            fi
          done

          chmod 600 ~/.ssh/known_hosts

          # Test SSH connection
          ssh -o BatchMode=yes -o StrictHostKeyChecking=no "${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}" "echo 'SSH connection successful'"

      - name: Create env file
        run: |
          if [ -z "${{ secrets.EC2_USER }}" ]; then
            echo "Error: EC2_USER secret is not set"
            exit 1
          fi

          ssh -o StrictHostKeyChecking=no "${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}" "echo '${{ secrets.ENV_VARS }}' > ~/lifehacksjapan-forum/.env"
